[package]
name = "dhcpv6-parser"
version = "0.1.0"
authors = ["Thomas WACHE <thomas.wache@intradef.gouv.fr>"]
edition = "2018"

[lib]
name = "dhcpv6_parser"
crate-type = ["staticlib"]

[dependencies]
enum-primitive-derive = "^0.1"
nom = "^5"
num-traits = "^0.2"
